### ISSUE TITLE
Verify Parsing: false on umap file

### ISSUE THREAD

**Issue by Giwayume** [atenfyr/UAssetAPI#1]
**Describe the bug**
I have a file that does not verify parsing:

[m01SIP_000_BG.zip](https://github.com/atenfyr/UAssetAPI/files/7182064/m01SIP_000_BG.zip)

**To Reproduce**
```
AssetWriter y = new AssetWriter(@"PATH\TO\m01SIP_000_BG.umap", null, null); // no skips, no force reads
Console.WriteLine("Data preserved: " + (y.VerifyParsing() ? "YES" : "NO"));
```

**Expected behavior**
Please fix so parsing is verified.

**Desktop (please complete the following information):**
 - OS: Windows 7 64

**Comment by atenfyr** [comment]
Hey there. The asset should now parse properly on the 1.0 (near-complete rewrite) branch. Thanks for sending this in.

**Comment by Giwayume** [comment]
Ok, I'm glad I didn't get that far with using master 😢

**Comment by Giwayume** [comment]
@atenfyr the 1.0 code doesn't seem to auto detect engine version like master. Or maybe master didn't care. So specifying version is required now?

![image](https://user-images.githubusercontent.com/4075314/133829038-7bee3c18-de40-4ef3-9eeb-f05c6b71b3e9.png)

**Comment by atenfyr** [comment]
@Giwayume If provided a versioned asset, UAssetAPI will detect the version within the asset and automatically set the version, but it no longer will attempt to guess the version of unversioned assets since such a guess is inherently unreliable.
