### ISSUE TITLE
UAssetAPI serializes and deserializes FNames differently than Unreal Engine

### ISSUE THREAD

**Issue by jordanbtucker** [atenfyr/UAssetAPI#10]
**Describe the bug**
UAssetAPI serializes and deserializes FNames differently than Unreal Engine.

**To Reproduce**
1. Instantiate an `FName` by calling its static `FromString` method with the argument `"HelloWorld_0"`.
2. Call the `ToString` method on the `FName`.
3. Note that it returns `"HelloWorld_0(0)"` instead of `"HelloWorld_0"`.
4. Evaluate the `Value` and `Number` properties of the `FName`.
5. Note that they evaluate to an `FString` with the value `"HelloWorld_0"` and the int `0`, respectively, instead of an `FString` with the value `"HelloWorld"` and the int `1`.

**Expected behavior**
UAssetAPI should parse and serialize FNames in the same way that Unreal Engine does. (See **Additional context**.)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version or Commit: 56815c926add2b563cf4ef8ce2b29e624f9adc42

**Additional context**
FNames are serialized as an index into a name list and an instance number. In Unreal Engine, when an FName is deserialized, non-zero instance numbers are decremented and appended to the name following an underscore. For example, an FName pointing to `"HelloWorld"` with an instance number of `2` would be deserialized as `"HelloWorld_1"` in Unreal Engine. UAsset API will instead deserialize this FName as `"HelloWorld(2)"`.

For FNames with an instance number of `0`, Unreal Engine does not append the instance number, however UAssetAPI does. For example, an FName pointing to `"HelloWorld"` with an instance number of `0` would be deserialized as `"HelloWorld"` in Unreal Engine. UAssetAPI will instead deserialize this FName as `"HelloWorld(0)"`.

The reason that Unreal Engine uses FName instance numbers is to reduce the memory and file space needed to store similar names. For example, if you had several names that start with `HelloWorld_` and end with different numbers, Unreal Engine can store these similar names as one entry in a table. So rather than having to store `HelloWorld_0`, `HelloWorld_1`, and `HelloWorld_2` in the name list, Unreal Engine can just store `HelloWorld` once and use the name index and instance numbers when referencing similar names.

You can find more information in the [FName](https://docs.unrealengine.com/4.27/en-US/ProgrammingAndScripting/ProgrammingWithCPP/UnrealArchitecture/StringHandling/FName/) documentation and in the [`ParseNumber`](https://github.com/EpicGames/UnrealEngine/blob/d94b38ae3446da52224bedd2568c078f828b4039/Engine/Source/Runtime/Core/Private/UObject/UnrealNames.cpp#L1927) function in UnrealNames.cpp. (Although I think the comments in [older versions](https://github.com/EpicGames/UnrealEngine/blob/0a14a8d537a31ecc77488ced41dbaa0166612ef8/Engine/Source/Runtime/Core/Private/UObject/UnrealNames.cpp#L1051) are clearer.)

Essentially, when an FName is serialized, Unreal Engine checks to see if the string ends with `_` followed by either (a) a single `0` or (b) `1`-`9` followed by zero or more digits. If the string matches this pattern, then the digits are converted to a decimal number, incremented by one, and stored as the instance number, and everything before the `_` is stored as the name to index. Otherwise, the full string is stored as the name to index and the instance number is stored as `0`. Note that numeric suffixes cannot be prefixed with `0`, i.e. `HelloWorld_0` is a match and stored as `Name = "HelloWorld", Number = 1`, while `HelloWorld_01` is not a match and is stored as `Name = "HelloWorld_01", Number = 0`.

The following regular expression can match strings that should be serialized with non-zero instance numbers.

```js
/^(.+)_(0|[1-9]\d*)$/
```

If matched, group 1 contains the name and group 2 contains the number that should be parsed and incremented before storing as the instance number. If not matched, the whole string should be stored as the name and the instance number should be `0`.

Sorry for the long description. Let me know if you want a PR.

**Comment by atenfyr** [comment]
Fixed in 44401ba. Thank you for the helpful writeup
