### ISSUE TITLE
House of Ashes error

### ISSUE THREAD

**Issue by lostprophet** [atenfyr/UAssetAPI#13]
Hi!
House of Ashes uses Unreal Engine 4, 4.26.2.
When I try to open the .uexp/.uasset with the latest UassetGUI (using the latest UassetAPi compiled today) to extract the text, I receive the following error messages:
[https://i.imgur.com/5y5zbIs.png](url)
[https://i.imgur.com/CfjrZbz.png](url)
Copy of the .uexp/.uasset I'm having problems with: [https://www19.zippyshare.com/v/2SNkl7np/file.html](url)

**Comment by atenfyr** [comment]
I can't access the asset at that link, please send another copy
