### ISSUE TITLE
Failed to maintain binary equality

### ISSUE THREAD

**Issue by PaperStrike** [atenfyr/UAssetAPI#14]
**Describe the bug**
This asset failed to maintain binary equality when editing.

**To Reproduce**
1. Extract the two files in [DT_Imitation.zip](https://github.com/atenfyr/UAssetAPI/files/8158640/DT_Imitation.zip).
2. Open with uassetGUI.
3. See error.

Unreal Engine version: 4.26
Game: Tower of Fantasy

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version or Commit: 44401ba

**Additional context**
The game do run into some strange problems after modifying this asset.

**Comment by atenfyr** [comment]
Fixed in a238aa6
