### ISSUE TITLE
Clothing Asset/Cloth Data Export failing to read.

### ISSUE THREAD

**Issue by VelouriasMoon** [atenfyr/UAssetAPI#16]
When loading a skeletal mesh with clothing the ClothingAsset will fail to read leaving just a raw export. I've tracked the issue down to 8 extra bytes in between 2 of the properties, LodData and LodMap, which causes LodMap and properties after it to become offset and thus causes to whole export to fail to read.  

Forcing the `MainSerializer.Read()` to skip these 8 bytes will allow the cloth data to be read properly because makes the file unstable and crashes the game after saving.  

This is the code I used in my testing to get the file to at least phrase in memory if it help, added after `FName type = reader.ReadFName();` in `MainSerializer.Read()`.  
```C#
if (type.Value.Value == "LodMap")
{
    name = new FName("LodMap");
    type = reader.ReadFName();
}
```

Sample File: (Code Vein, UE Version 4.18)
[https://mega.nz/file/owNHlRaQ#1P7scpm4qJ6O0hOkujrt__JO5b3snitz-pI1uwusjiU](https://mega.nz/file/owNHlRaQ#1P7scpm4qJ6O0hOkujrt__JO5b3snitz-pI1uwusjiU)

**Comment by atenfyr** [comment]
Good work in isolating those eight bytes as the issue! Those bytes are actually two empty FMeshToMeshVertData arrays (TransitionUpSkinData & TransitionDownSkinData) that are stored as part of the FClothLODData struct (LodData is an FClothLODData array). See [ClothLODData.h](https://github.com/EpicGames/UnrealEngine/blob/46544fa5e0aa9e6740c19b44b0628b72e7bbd5ce/Engine/Source/Runtime/ClothingSystemRuntimeCommon/Public/ClothLODData.h#L51), [ClothLODData.cpp](https://github.com/EpicGames/UnrealEngine/blob/46544fa5e0aa9e6740c19b44b0628b72e7bbd5ce/Engine/Source/Runtime/ClothingSystemRuntimeCommon/Private/ClothLODData.cpp#L34), [SkeletalMeshTypes.h](https://github.com/EpicGames/UnrealEngine/blob/46544fa5e0aa9e6740c19b44b0628b72e7bbd5ce/Engine/Source/Runtime/Engine/Public/SkeletalMeshTypes.h#L59), [SkeletalMesh.cpp](https://github.com/EpicGames/UnrealEngine/blob/46544fa5e0aa9e6740c19b44b0628b72e7bbd5ce/Engine/Source/Runtime/Engine/Private/SkeletalMesh.cpp#L249)
