### ISSUE TITLE
System.NullReferenceException when opening a .uasset file

### ISSUE THREAD

**Issue by MarcosVLl2** [atenfyr/UAssetAPI#21]
Tried to open some files from the game Will To Live Online, found myself with error System.NullReferenceException in line 203 of MainSerializer.cs

1. Open UAssetGUI.exe
2. Set UE4 version to 4.26
3. Open file "NPS_TeleportCCD"
4. Error!

**Expected behavior**
The file opens up correctly and I can see it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 build 22000.co_release.210604-1628
 - Version or Commit: UAssetGUI v1.0.0.4 (GUI e7b811d - API 354f38f)

**Additional context**
Only happened with this file in specific, here I also add a similar file that works
[Twofiles.zip](https://github.com/atenfyr/UAssetAPI/files/8846959/Twofiles.zip)

**Comment by LongerWarrior** [comment]
fixed in new UAssetGUI release https://github.com/atenfyr/UAssetGUI/commit/be5e203af7e43f9d8c4df404f1a4ba46c97bfa0c
