### ISSUE TITLE
Encountered 1 unknown property types: Field Path Property

### ISSUE THREAD

**Issue by Marold57** [atenfyr/UAssetAPI#22]
Hey :D

**Describe the bug**
"Encountered 1 unknown property types: Field Path Property" when open the UAsset with UAsset API. Game Engine Version is 4.26.1.0
[Necromunda Hired Gun 4.26.1.0.zip](https://github.com/atenfyr/UAssetAPI/files/8854731/Necromunda.Hired.Gun.4.26.1.0.zip)

I think this Files have Values about Damage, Magazine Size and more from Weapons that i would like to change.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Version or Commit: [fc49e96]

Thanks and have a nice day!

**Comment by atenfyr** [comment]
Implemented in f32cc42
