### ISSUE TITLE
Checksums?

### ISSUE THREAD

**Issue by Dastano** [atenfyr/UAssetAPI#23]
Hey,

do every Uasset File got a Checksum? I just checking on a Game, it works fine with the Tool (most of the Time, except some small Files, I could sent in private if needed, since they are use 4.27.1 + own Source)

However, the Server refuses the connection, because it looking for a checkSum, so I am curious, if this is a field we could read from the File?

**Comment by atenfyr** [comment]
The asset format does not provide for any checksum or error detection algorithm. However, a SHA1 hash is included with every file record in a .pak file that can be used to verify integrity
