### ISSUE TITLE
BlueprintReplicationCondition does not always exist on UProperty

### ISSUE THREAD

**Issue by CrystalFerrai** [atenfyr/UAssetAPI#25]
In UProperty.Read is this block of code (and there is similar in Write):
```
if (reader.Asset.GetCustomVersion<FReleaseObjectVersion>() >= FReleaseObjectVersion.PropertiesSerializeRepCondition)
{
    BlueprintReplicationCondition = (ELifetimeCondition)reader.ReadByte();
}
```
I am working with UE 4.27 blueprint assets from the game Icarus, and that byte is not present in properties that I encountered. That check returns true for any version from 4.22 onwards. However, I suspect the presence of this value depends on more than just the engine version. Perhaps it is only present of the property flag `CPF_RepNotify` is set?

**Comment by atenfyr** [comment]
Good to see you again, Crystal!

The code in question is pretty much just a direct copy of [this line of code within PropertyPrivate.cpp](https://github.com/EpicGames/UnrealEngine/blob/4.27/Engine/Source/Runtime/CoreUObject/Private/UObject/PropertyPrivate.cpp#L103), which is one of the only places in the codebase where BlueprintReplicationCondition is mentioned. Given this code, there are only really a few ways I can see it not being serialized:
- The current FReleaseObjectVersion custom version is set to something before FReleaseObjectVersion::PropertiesSerializeRepCondition (see EpicGames/UnrealEngine@da64b0e), which by default would be before 4.21, but could be manually changed with a custom engine build or in any versioned asset (which sounds silly)
- The UProperty::Serialize method returns before the field can be serialized, or is never called at all for some reason
- The code in question serializing the field was removed in a custom engine build (which sounds silly)

So this is a very strange issue... perhaps the byte actually is being serialized and there is some issue in another part of serialization, but I can't really say anything detailed without looking directly at an asset with this problem.

**Comment by CrystalFerrai** [comment]
The interesting thing is that all the memory seems to line up perfectly if we skip that byte. The value of the byte in the assets I have never matches up with any of the enum values, and reading it causes things to fail soon after because of not being aligned to the data anymore.

I looked at the code you linked from the engine. There are a couple things I can see that could cause that code to never run.
1. UProperty::Serialzie is virtual, so any derived UProperty class could behave differently. However, all the overloads I could quickly find do call the base class method.
2. That specific line calls FArchive's `operator<<` which calls serialize, which is a virtual method that has an empty implementation in the base class. Without knowing which specific derived class is being used, I cannot tell what the implementation actually does.

**Comment by CrystalFerrai** [comment]
I tried to reproduce the issue again so I could get more information and now none of  the assets I am trying ever end up calling the UProperty.Read function at all. I don't remember what assets I was looking at before . So I guess don't worry about it. I will report back if I manage to encounter it again.
