### ISSUE TITLE
Failed to maintain binary equality

### ISSUE THREAD

**Issue by Aleirdra** [atenfyr/UAssetAPI#28]
Game       :  Vampyr
Unreal      :  4.15.3
UAssetGUI:  v1.0.0.0-alpha.6
OS            :  Windows 10 Home (10.0.19044)

Heya! Got a game that the API seems to be having an issue parsing the uassets. Files attached.

Thank you for all your hard work!

[VampyrUassets.zip](https://github.com/atenfyr/UAssetAPI/files/9366903/VampyrUassets.zip)

**Comment by LongerWarrior** [comment]
there are no uexp files, so can't fix this
