### ISSUE TITLE
Parsing master material exports

### ISSUE THREAD

**Issue by Giwayume** [atenfyr/UAssetAPI#3]
**Is your feature request related to a problem? Please describe.**
Is it possible to parse these export types? 
Material, MaterialExpressionMaterialFunctionCall, MaterialExpressionStaticSwithParameter, MaterialExpressionTextureSampleParameter2D...

[M_COM_DetailMaster_B.zip](https://github.com/atenfyr/UAssetAPI/files/7256956/M_COM_DetailMaster_B.zip)

**Describe the solution you'd like**
Looking to be able to pull basic information from master materials in order to replicate them.

**Comment by Waffle1434** [comment]
#45
