### ISSUE TITLE
Failed to maintain binary equality

### ISSUE THREAD

**Issue by JoyKkk** [atenfyr/UAssetAPI#33]
Game: Dark Deception
Unreal version: 4.24
UAssetGUI version: v1.0.0.0-alpha.6
OS: Windows 10 Pro

**Describe the bug**
When I'm opening the uasset file, firstly it says "Failed to parse 1 exports", then it says "Failed to maintain binary equality"
How can I fix this?

[DarkDeceptionUasset.zip](https://github.com/atenfyr/UAssetAPI/files/9846577/DarkDeceptionUasset.zip)

**Comment by atenfyr** [comment]
You cannot open a .uasset file without its corresponding .uexp file present in the same directory
