### ISSUE TITLE
Solution does not build as UAssetGUI is referenced in solution file but not included in repo

### ISSUE THREAD

**Issue by agc93** [atenfyr/UAssetAPI#38]
**Describe the bug**
A clean clone of this repository does not build successfully as the solution file references the `UAssetGUI` project, which is in its own repo and not referenced here. Is this supposed to be included as a submodule?

**To Reproduce**
1. Clone this repository
2. Run `dotnet build` (or attempt to build the solution with any other tool)
3. The build will fail as the `UAssetGUI` project is not present

**Expected behavior**
Ideally, this repo should be able to be built, or the extra steps documented. If UAssetGUI was added as a submodule, anyone could just `git submodule update --init ` and get the right version of UAssetGUI immediately present in their environment.

**Desktop:**
 - OS: any, but tested on Windows 10
 - Version or Commit: [1a43738](https://github.com/atenfyr/UAssetAPI/commit/1a43738926c55cb52c77d63463bffc8c3ca90fb7)

**Comment by atenfyr** [comment]
I have rearranged the project structure such that you have the option to build UAssetAPI with a solution that does not include UAssetGUI (which may be useful if you are not using Visual Studio). Please see the revised build instructions in the [README.md](https://github.com/atenfyr/UAssetAPI/blob/master/README.md#Compilation) file if needed.
