### ISSUE TITLE
Update to newer `csproj` format to support newer SDKs

### ISSUE THREAD

**Issue by agc93** [atenfyr/UAssetAPI#39]
**Is your feature request related to a problem? Please describe.**
The old 2015-style `csproj` files are unwieldy to work with and the `dotnet` CLI (and other modern build tools) often don't support them properly, making building this project unnecessarily difficult.

**Describe the solution you'd like**
Ideally, it should be possible to replicate all the current behaviour of the existing project file while also updating to correctly target .NET 6 and retaining Framework 4.6.x support. If you're interested in this, I'm also happy to put together a PR to update UAssetAPI to use the newer format as I've done this for my own fork (from a much earlier state of this repo).

**Additional context**
The newer formats are still fully supported by Visual Studio 2017 or later, but this would also make it easier to work with UAssetAPI for those not using Visual Studio (like myself).

**Comment by atenfyr** [comment]
Seems fair enough to me. Completed in c480267
