### ISSUE TITLE
Material Exports Not Supported

### ISSUE THREAD

**Issue by Waffle1434** [atenfyr/UAssetAPI#45]
**Describe the bug**
The following fail to parse correctly:
`MaterialExpressionAdd`, `MaterialExpressionAppendVector`, `MaterialExpressionClamp`, `MaterialExpressionDesaturation`, `MaterialExpressionLinearInterpolate`, `MaterialExpressionMaterialFunctionCall`, `MaterialExpressionMultiply`, `MaterialExpressionStaticSwitchParameter`, probably more `MaterialExpression...`'s

The following work:
`MaterialExpressionComment`, `MaterialExpressionScalarParameter`, `MaterialExpressionTextureCoordinate`, `MaterialExpressionTextureSampleParameter2D`, `MaterialExpressionVectorParameter`

Based on setting a breakpoint, the first property of the struct will get read in mostly right, but its not reading the correct number of bytes per property and thus the next properties will be a garbled mess.

`MaterialExpressionComment` Example:
![image](https://user-images.githubusercontent.com/8021358/208573542-2e01d9a5-ff80-43cb-bbc6-fffccda828da.png)

`MaterialExpressionAdd` Example:
[MaterialExpressionAdd_0.zip](https://github.com/atenfyr/UAssetAPI/files/10264588/MaterialExpressionAdd_0.zip)
![image](https://user-images.githubusercontent.com/8021358/208573588-3745173f-8f8d-4aaf-b0b3-3a275dd0229c.png)
Expected (from `.T3D`):
```
Begin Object Name="MaterialExpressionAdd_0"
  A=(Expression=MaterialExpressionTextureSampleParameter2D'"M_Base_Trim:MaterialExpressionTextureSampleParameter2D_2"',OutputIndex=1,Mask=1,MaskR=1)
  B=(Expression=MaterialExpressionTextureSampleParameter2D'"M_Base_Trim:MaterialExpressionTextureSampleParameter2D_2"',OutputIndex=2,Mask=1,MaskG=1)
  MaterialExpressionEditorX=-368
  MaterialExpressionEditorY=80
  MaterialExpressionGuid=C4E2389348ECEC059C2245B9DC52BF18
  Material=Material'"M_Base_Trim"'
End Object

```
It looks like it trips up on any property that has the format:
`<PropertyValue>=(Expression=<Class>'"<Material>:<ExportName>"',<Key>=<Value>,...)`

Sifting through the raw hex, I'm able to see for example, `0x0C` is index 12 in the name array ("A", correct). `0x0F` is name index 15, "B" for the second property, but in practice the reader tries to read the name index 5 bytes ahead of where 15 actually is. `0x43` corresponds to "Export Information" index 67 `MaterialExpressionTextureSampleParameter2D_2`. After the Export Object Index, it seems to have an array of 32bit values in the same order as listed in the T3D (ex. 1,1,1).

**To Reproduce**
1. Open my supplied Material `.uasset`
2. Set a breakpoint in `UAsset.Read` line `1317` and step in
3. Notice the first property is correct, sequential ones aren't, thus exceptions are thrown and they fallback to Raw view

Material `.uasset`, also in `.T3D` form (which is text readable):
[M_Base_Trim.zip](https://github.com/atenfyr/UAssetAPI/files/10264443/M_Base_Trim.zip)

If applicable, provide a copy of the asset that can be used to reproduce the bug, along with the Unreal Engine version that the asset was cooked with and the game that it is from.

**Expected behavior**
Expected to parse all properties of each export struct.

**Desktop:**
 - OS: Windows 10 Latest
 - Version or Commit: 11/15/22 `d9aa3575066cf1c82af68e9ad2ff86abe5254308`
 - Asset is taken from a free asset in a 4.27 project, but UAssetGUI suggests its v4.16

**Comment by Waffle1434** [comment]
It looks like it trips up on an property that has the format `<PropertyValue>=(Expression=<Class>'"<Material>:<ExportName>"',...)`

**Comment by Waffle1434** [comment]
Also fails to maintain binary equality

**Comment by Waffle1434** [comment]
It would seem the property parsing could use a fallback in the event the type isn't recognized, right now the entire export falls back instead. "Raw Data" could be displayed on a per-property basis by reading the property's length in bytes. `StructProperty` in particular is vulnerable to this, I was able to get this working in python for something I'm working on. After reading the struct type from the "header", if its not recognized I read the raw bytes using `leng`. This successfully reads all properties even when unrecognized.

**Comment by Waffle1434** [comment]
Binary layout of ExpressionInput struct type is:
![image](https://user-images.githubusercontent.com/8021358/209077439-41ce4916-b286-4cef-9f74-83421b2af88b.png)
This worked for my purposes:
![image](https://user-images.githubusercontent.com/8021358/209077683-de562f78-2f7d-4003-a760-abb16f3697cd.png)

**Comment by DrCondo** [comment]
I've been looking for a tool to get the node setup for cooked materials and this looks pretty promising. Definitely interested in seeing something this work, since the best I can get with FModel/CUE4Parse exporting is the initial header section directly connected to the output node, and umodel only seems to provide the texture inputs. I'm not too familiar with this repository, but would you care to share how exactly you got those screenshots @Waffle1434 ? I've tried the JSON export already on a uasset+uexp I made using FModel on a project a packaged, got a similar problem I think to yours, something akin to the CreateBeforeCreateDependencies section having a gibberish string in the extra section. Definitely would appreciate some help with it if you care to share.

**Comment by Waffle1434** [comment]
> I've been looking for a tool to get the node setup for cooked materials and this looks pretty promising. Definitely interested in seeing something this work, since the best I can get with FModel/CUE4Parse exporting is the initial header section directly connected to the output node, and umodel only seems to provide the texture inputs. I'm not too familiar with this repository, but would you care to share how exactly you got those screenshots @Waffle1434 ? I've tried the JSON export already on a uasset+uexp I made using FModel on a project a packaged, got a similar problem I think to yours, something akin to the CreateBeforeCreateDependencies section having a gibberish string in the extra section. Definitely would appreciate some help with it if you care to share.

I'm working on a Blender addon to import .uasset materials into blender as a Blender node graph:
https://gist.github.com/Waffle1434/d2b518508e264f597ac4218560d637e8

My changes could hypothetically be backported into UAssetAPI so it can read them properly, but I don't exactly have the time.
