### ISSUE TITLE
I cant open this thing I need help

### ISSUE THREAD

**Issue by drtzusrurtsuz** [atenfyr/UAssetAPI#47]
Nearly every visual studio (2019 2017 2015 ) is not working 

This is whit  2015 
C:\Users\nexus\Downloads\UAssetGUI-master\UAssetAPI\UAssetAPI\UAssetAPI.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\nexus\Downloads\UAssetGUI-master\UAssetAPI\UAssetAPI\UAssetAPI.csproj'.  C:\Users\nexus\Downloads\UAssetGUI-master\UAssetAPI\UAssetAPI\UAssetAPI.csproj

C:\Users\nexus\Downloads\UAssetGUI-master\UAssetAPI\UAssetAPI.Tests\UAssetAPI.Tests.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\nexus\Downloads\UAssetGUI-master\UAssetAPI\UAssetAPI.Tests\UAssetAPI.Tests.csproj'.  C:\Users\nexus\Downloads\UAssetGUI-master\UAssetAPI\UAssetAPI.Tests\UAssetAPI.Tests.csproj

C:\Users\nexus\Downloads\UAssetGUI-master\UAssetGUI\UAssetGUI.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\nexus\Downloads\UAssetGUI-master\UAssetGUI\UAssetGUI.csproj

C:\Users\nexus\Downloads\UAssetGUI-master\UAssetAPI\UAssetAPI.Benchmark\UAssetAPI.Benchmark.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\nexus\Downloads\UAssetGUI-master\UAssetAPI\UAssetAPI.Benchmark\UAssetAPI.Benchmark.csproj'.  C:\Users\nexus\Downloads\UAssetGUI-master\UAssetAPI\UAssetAPI.Benchmark\UAssetAPI.Benchmark.csproj

**Comment by atenfyr** [comment]
If you want to download a pre-built binary of UAssetGUI, you can find them in the Releases section of the UAssetGUI repository here: [https://github.com/atenfyr/UAssetGUI/releases/tag/v1.0.0.0-alpha.7](https://github.com/atenfyr/UAssetGUI/releases/tag/v1.0.0.0-alpha.7)

If you want to compile UAssetGUI, please follow the instructions in [the README of UAssetGUI](https://github.com/atenfyr/UAssetGUI#initial-setup). Notably, you will have to use git to pull the required submodules to compile UAssetGUI.

**Comment by drtzusrurtsuz** [comment]
Thank you !!
