### ISSUE TITLE
.umap failed to maintain binary equality

### ISSUE THREAD

**Issue by bananaturtlesandwich** [atenfyr/UAssetAPI#5]
**Issue**
This .umap failed to maintain binary equality when edited with uassetAPI

**To Reproduce**
1. Download the assets
2. Open with uassetGUI with the version of UE4 set to 4.25
3. see the failed to verify binary equality error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version or Commit: [this one](https://github.com/atenfyr/UAssetAPI/commit/e756426)
 
**Context**
If you are unable to or do not have enough time that is fine because my project does not solely rely on this one fil
[Sealed_Land.zip](https://github.com/atenfyr/UAssetAPI/files/7463752/Sealed_Land.zip)

**Comment by atenfyr** [comment]
Thanks for sending this in, fixed in b65ecf2
