### ISSUE TITLE
Export exports as json

### ISSUE THREAD

**Issue by warflash** [atenfyr/UAssetAPI#50]
**Is your feature request related to a problem? Please describe.**
I want to build my own cli tool to traverse the tables of a uasset and export certain things as json. For a prototype I'd also be happy with just exporting the structure of the entire asset similar to how saving to json works in the UAsset GUI

**Describe the solution you'd like**
I'm not sure this is an actual issue/request but I'd appreciate some docs/guidance on how to work with the data `new UAsset()` generates as the readme unfortunately didn't help much. 

Appreciate any help/feedback!

**Comment by atenfyr** [comment]
Howdy,

Everything that is displayed in UAssetGUI closely aligns with the way that data is stored in memory in UAssetAPI; imports can be accessed through the UAsset.Imports field, which contains a list of Import objects, exports can be accessed through the UAsset.Exports field, etc. The bulk of the data of a .uasset file is contained within its exports, which you can access with the UAsset.Exports field, which contains a list of Export types. Different exports have different types (you can see all the supported export types in [this folder](https://github.com/atenfyr/UAssetAPI/tree/master/UAssetAPI/ExportTypes)), but the most common type of export is NormalExport, which contains standard tagged properties in a list that typically represents a particular Unreal struct. Each export type and property type has different data, meaning that you may need to cast exports and properties to their own types to retrieve all the relevant data from them. Several unit tests also exist, which may help you get a feel for the syntax of the API @ https://github.com/atenfyr/UAssetAPI/blob/master/UAssetAPI.Tests/AssetUnitTests.cs#L390.

atenfyr

**Comment by warflash** [comment]
Thank you, I appreciate the thorough response! 
Got familiar with the setup over the past few days and making progress now - thanks a lot for the work on this project 💚
