### ISSUE TITLE
F1 Manager 23 failed to maintain binary equality

### ISSUE THREAD

**Issue by fibonatee** [atenfyr/UAssetAPI#53]
**Describe the bug**
failed to maintain binary equality for uasset files.

**To Reproduce**
If applicable, provide a copy of the asset that can be used to reproduce the bug, along with the Unreal Engine version that the asset was cooked with and the game that it is from.
[RaceSimDataAsset.zip](https://github.com/atenfyr/UAssetAPI/files/12549967/RaceSimDataAsset.zip)

**Screenshots**
![Snap 2023-08-02 at 12 03 24](https://github.com/atenfyr/UAssetAPI/assets/140854594/28f921ee-b8a3-4a79-b600-9deaf5b11c13)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Game UE version should be 5.1

Thanks a million!

**Comment by trumank** [comment]
Do you have the `.usmap` mappings file for this asset? Can't to parse without it

**Comment by fibonatee** [comment]
> Do you have the `.usmap` mappings file for this asset? Can't to parse without it

Hi there, Yes try this one -https://mega.nz/file/FscVVahD#b1vSCjnmedYklxT_RFyMU68iPxE_lVpZY12-66i8pyE

Thank you so much

**Comment by fibonatee** [comment]
Any news on this uasset guys? Thanks!
