### ISSUE TITLE
Failed To Parse Export

### ISSUE THREAD

**Issue by Kaiverrus** [atenfyr/UAssetAPI#57]
Keep getting "Failed to parse 1 exports!" when trying to open any files from this game
Game: F1 Manager 2023
Engine: I believe run on 5.1 since using 5.1 below won't work at all

I attach few files to be tested
[F1M23.zip](https://github.com/atenfyr/UAssetGUI/files/12196560/F1M23.zip)

**Comment by fibonatee** [comment]
> yes that is the problem with UnrealMappingsDumper generate incorrect mapping for big enums here is valid mappings [F1Manager2023.zip](https://github.com/atenfyr/UAssetGUI/files/12207426/F1Manager2023.zip)

Hello, may I know how did you fix the incorrectly generated big enums problem? I thought the mapping could have changed after game updates. so I generate a new one but Fmodel still gives the "Index was out of range" error.

Attached new mapping:
[Mappings.zip](https://github.com/atenfyr/UAssetAPI/files/14113315/Mappings.zip)
