### ISSUE TITLE
.uasset that fails to maintain binary equality

### ISSUE THREAD

**Issue by bananaturtlesandwich** [atenfyr/UAssetAPI#6]
Some more uassets that fail to parse

- Open the .uasset with uassetGUI/API
- There's a warning saying binary equality cannot be maintained with the asset
- Because of this properties in the assets can't be modified

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version or Commit: https://github.com/atenfyr/UAssetAPI/commit/e756426
 
**Files**
[Player_Character_BP.zip](https://github.com/atenfyr/UAssetAPI/files/7629256/Player_Character_BP.zip)

*Sorry about this it would just be great to be able to modify the player character*

**Comment by atenfyr** [comment]
Unable to replicate as of 1ea96c6. Try updating to the newest commit and see if the issue persists
