### ISSUE TITLE
[Paid Feature Request] UE 5.3 Support

### ISSUE THREAD

**Issue by ShadyKutz** [atenfyr/UAssetAPI#62]
Task: Update UAssetAPI for UE 5.3 Compatibility – $5,000 Bounty Pool!
We are officially announcing a bounty of $5,000 to update a crucial open-source tool for Unreal Engine modding, making them compatible with Unreal Engine 5.3: [UAssetAPI](https://github.com/atenfyr/UAssetAPI). This bounty pool will be paid out to single individuals or shared between the top 3 contributors who successfully achieve this milestone.

How to Participate:
- Fork the repository and begin working on updating the codebase for UE 5.3 compatibility
- Submit with detailed descriptions of your updates and improvements
- Ensure your code is thoroughly tested 
- Contact media@voidinteractive.net to confirm

**Bounty Distribution**:
The $5,000 bounty pool will be paid out to single individuals or shared between the top 3 contributors who successfully achieve this milestone.

Help us make this essential modding tool compatible with UE 5.3 and earn your share of the bounty! If you have any questions, feel free to reach out via Github or email: media@voidinteractive.net

**Comment by atirathk** [comment]
Could you share any specific errors or issues that come up when you try to use this tool with UE 5.3?
