### ISSUE TITLE
Failed to maintain binary equality

### ISSUE THREAD

**Issue by X-Zero-L** [atenfyr/UAssetAPI#64]
**Describe the bug**
This asset failed to maintain binary equality when editing.

**To Reproduce**
1. Extract files in 
[Mappings.zip](https://github.com/atenfyr/UAssetGUI/files/14124279/Mappings.zip)
2. Open with uassetGUI.
3. See error.

Unreal Engine version: 5.2
Game: Palworld

**Screenshots**
![image](https://github.com/atenfyr/UAssetGUI/assets/98764734/f421ddf0-9c8f-41cc-a097-2ea101d1c715)
![image](https://github.com/atenfyr/UAssetGUI/assets/98764734/c197526c-8aa2-4adc-9f6e-8a0cbfc07ce6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version or Commit: 1.0.0.8

**Comment by atenfyr** [comment]
Fixed as part of #58. The comment underneath that issue about including the asset `/Game/Pal/Blueprint/MapObject/Components/BP_InteractableBox` also applies here - pull the latest commit and try that
