### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by MinecrackTyler** [atenfyr/UAssetAPI#68]
**Describe the bug**
I have a .umap and uexp combo packed in ue 4.24 that refuses to open in newer version above 1.0.0.5 with the error System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count

**To Reproduce**
1. Open the newest commit and or release of UAssetGui
2. Open the attached file
3. See error
From UE 4.24, game is [Project Wingman](https://store.steampowered.com/app/895870/Project_Wingman/)

**Expected behavior**
It should open

**Screenshots**
![image](https://user-images.githubusercontent.com/45902457/202078201-d37907f1-a20b-4d93-88e5-b2ae1486fb4d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version or Commit: 1.0.0.7

**Additional context**
I dont know if this is an issue with the file, or maybe with the program, but it would be nice to still open if able and maybe point out the issue
Alternatively, if someone can find what is causing the issue so i can change it.
Thank you
[C_M22.zip](https://github.com/atenfyr/UAssetGUI/files/10017957/C_M22.zip)

**Comment by LongerWarrior** [comment]
seems like engine modification, cause WorldTileInfoOffset value is lower than an actual offset in the asset by 240 bytes.
for this game it should be like this: WorldTileInfoDataOffset = reader.ReadInt32()+240; (and corresponding changes to the write section to maintain binary equality)
