### ISSUE TITLE
Binary Inequality UE 4.10.4

### ISSUE THREAD

**Issue by walkinet** [atenfyr/UAssetAPI#72]
[bp_eyeofreach.zip](https://github.com/user-attachments/files/15870959/bp_eyeofreach.zip)

**Comment by rndtrash** [comment]
I took a look at the file, and it seems it has an additional 6 bytes of data between the AssetRegistryDataOffset and BulkDataStartOffset. I looked at every public version of UE4, but neither had anything new between them. Do they use a custom version?

![HxD_hzsxOZt6RI](https://github.com/atenfyr/UAssetAPI/assets/6745157/263c49e4-b2e5-4e6f-af38-755bb8f4348b)

**Comment by Nythys** [comment]
> I took a look at the file, and it seems it has an additional 6 bytes of data between the AssetRegistryDataOffset and BulkDataStartOffset. I looked at every public version of UE4, but neither had anything new between them. Do they use a custom version?
> 
> ![HxD_hzsxOZt6RI](https://private-user-images.githubusercontent.com/6745157/340870022-263c49e4-b2e5-4e6f-af38-755bb8f4348b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3Nzg2MzgsIm5iZiI6MTcyMjc3ODMzOCwicGF0aCI6Ii82NzQ1MTU3LzM0MDg3MDAyMi0yNjNjNDllNC1iMmU1LTRlNmYtYWYzOC03NTViYjhmNDM0OGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDRUMTMzMjE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmZhZGFkNjk5YWE5YTk5MDk3MDVkNTJiYjQzYmRjYWQwMmQ5NTdhNGViOTRhM2QyNGYxYzQyM2VmZWFlOTg4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JzNuFwR8AWk6LQbI0Rz6yvwsx4aYSUgPq0H4nfbfTlg)

yes the game uses a custom version of unreal engine, I think it must be a bit like Days Gone
