### ISSUE TITLE
Failed To Parse file

### ISSUE THREAD

**Issue by GGavin0** [atenfyr/UAssetAPI#73]
Any Idea how to fix this erro
<img width="289" alt="Screenshot 2024-06-18 120810" src="https://github.com/atenfyr/UAssetAPI/assets/170566481/f34f66a5-d902-46d1-9900-4ad8eead95ca">
r i switched my ver too 5.4 and i got this Game Fortnite

**Comment by atenfyr** [comment]
UAssetAPI doesn't support IO store/zen (see #36). You can try using [FModel](https://fmodel.app/), which is designed by and for Fortnite data miners
