### ISSUE TITLE
failed to maintain binary equality

### ISSUE THREAD

**Issue by Marold57** [atenfyr/UAssetAPI#9]
Hi and Happy New Year.

I have this Failure when i try to open any UAssets from the Game "Space Hulk Deathwing Enhanced Edition". Engine Version from the Game is 4.14.3 

**Describe the bug**
1. Open with UassetGUI.exe
2. Set Version to 4.14.3
3. Open Uasset
4. Failure Message: "failed to maintain binary equality"
![unknown_2022 01 06-18 30](https://user-images.githubusercontent.com/85793314/148426454-b07b9194-389d-4631-abb3-292ca3df4a46.png)
[Blueprints.zip](https://github.com/atenfyr/UAssetAPI/files/7823750/Blueprints.zip)

I have this Failure Message when i ty to open the UMAPS Files: Failed to Parse this file! .....
![unknown_2022 01 06-18 44](https://user-images.githubusercontent.com/85793314/148427275-03059ded-4b61-4475-b3e5-f808bb3f27be.png)
[Maps1.zip](https://github.com/atenfyr/UAssetAPI/files/7823789/Maps1.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version or Commit: v1.0.0.0-alpha.3 / atenfyr/UAssetAPI@e756426.
 
Thanks and have a nice day!

**Comment by LongerWarrior** [comment]
not an issue on latest commit atenfyr/UAssetAPI@124067f
